stages:

  preprocess:
    cmd: python code/datasets/preprocess.py
    deps:
      - code/datasets/preprocess.py
      - data/raw/pre-owned cars.csv
    outs:
      - data/processed/train.csv
      - data/processed/test.csv


  train:
    cmd: python code/models/train.py
    deps:
      - code/models/train.py
      - data/processed/train.csv
      - data/processed/test.csv
    outs:
      - models/model.pkl


  deploy:
    cmd: docker compose -f code/deployment/docker-compose.yml up --build -d
    deps:
      - models/model.pkl
      - code/deployment/docker-compose.yml